# -*- coding: utf-8 -*-
"""Image classification with pre built model- VGG16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-2Cps7CoxVxiJpJeRxXVGDHS8i7yljem

#Problem Statement:

The categorization of images into distinct classes is a pervasive task in computer vision, and it has a wide array of applications, including in pet identification and animal monitoring systems. In this assignment, we aim to develop a model capable of accurately distinguishing between cat and dog images. Instead of building a convolutional neural network (CNN) from scratch, we will leverage transfer learning using the VGG16 model, a pre-trained model on the ImageNet dataset. VGG16 is renowned for its effectiveness in image recognition tasks, but it does not have broad categories for cats and dogs. Therefore, we will utilize the convolutional (Conv) layers of VGG16 for feature extraction and add custom fully connected (Cat) layers for the classification task.

#Objectives:

##Utilize VGG16 for Feature Extraction:
● Employ the VGG16 model, excluding its top layers, to serve as a feature extractor for cat and dog images.

● Ensure the input images are of the correct size (150x150) and preprocessed appropriately to match VGG16’s requirements.

##Data Preprocessing and Augmentation:
Implement image data generators for real-time data augmentation, ensuring a robust and varied dataset for training the classification layers.

##Build and Train the Classification Model:
● Addcustom fully connected layers on top of the VGG16 model for the classification task.

● Freeze the convolutional layers of VGG16 to retain the pre-trained features and only train the added classification layers.

##Model Compilation and Training:
● Compile the model using stochastic gradient descent, categorical cross-entropy as the loss function, and accuracy as the evaluation metric.

● Train the model using the training data, and validate its performance using a validation set.

##Evaluate and Test the Model:
● Assess the model’s performance based on its accuracy in classifying images into cat or dog categories.

● Implement a prediction function to classify new images, providing the predicted category and the associated confidence level.

Install & Import Dependencies
"""

import subprocess
# Uninstall existing protobuf to prevent version conflicts
subprocess.run(["pip", "uninstall", "protobuf", "-y", "-q"], check=False)
# Install necessary packages, including tensorflow_datasets and a compatible protobuf
subprocess.run(["pip", "install", "tensorflow", "matplotlib", "numpy",
                "pillow", "scikit-learn", "tensorflow_datasets", "protobuf==3.20.3", "-q"], check=True)

import os
import random
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

import tensorflow as tf
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

# Constants
IMG_SIZE    = (150, 150)
BATCH_SIZE  = 32
EPOCHS      = 20
NUM_CLASSES = 2

print(f"TensorFlow version : {tf.__version__}")
print(f"GPU available      : {tf.config.list_physical_devices('GPU')}")

"""Download the Dataset"""

#   Uses tensorflow_datasets — no Kaggle account required.
#   First run downloads ~800 MB; subsequent runs use the cache.

import tensorflow_datasets as tfds

(raw_train, raw_validation, raw_test), metadata = tfds.load(
    'cats_vs_dogs',
    split=['train[:80%]', 'train[80%:90%]', 'train[90%:]'],
    with_info=True,
    as_supervised=True,
)

CLASS_NAMES = metadata.features['label'].names   # ['cat', 'dog']

print(f"Training   samples : {raw_train.cardinality().numpy()}")
print(f"Validation samples : {raw_validation.cardinality().numpy()}")
print(f"Test       samples : {raw_test.cardinality().numpy()}")
print(f"Class names        : {CLASS_NAMES}")

"""Preprocess & Augment the Data"""

#   VGG16 requires:
#     • Input shape  (150, 150, 3)
#     • Pixels processed via vgg16.preprocess_input (subtracts ImageNet means)
#
#   Augmentation is applied ONLY to training images.
# ─────────────────────────────────────────────────────────────────────────────

from tensorflow.keras.applications.vgg16 import preprocess_input

def resize_and_preprocess(image, label):
    """Resize to 150x150 and apply VGG16 channel-mean subtraction."""
    image = tf.image.resize(image, IMG_SIZE)
    image = tf.cast(image, tf.float32)
    image = preprocess_input(image)
    return image, label

def augment(image, label):
    """Random augmentations for training robustness."""
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_brightness(image, max_delta=0.2)
    image = tf.image.random_contrast(image, lower=0.8, upper=1.2)
    image = tf.image.random_saturation(image, lower=0.8, upper=1.2)
    # Random zoom via crop then resize
    crop_frac = tf.random.uniform([], 0.75, 1.0)
    h = tf.cast(tf.cast(IMG_SIZE[0], tf.float32) * crop_frac, tf.int32)
    w = tf.cast(tf.cast(IMG_SIZE[1], tf.float32) * crop_frac, tf.int32)
    image = tf.image.random_crop(image, [h, w, 3])
    image = tf.image.resize(image, IMG_SIZE)
    return image, label

AUTOTUNE = tf.data.AUTOTUNE

train_ds = (
    raw_train
    .map(resize_and_preprocess, num_parallel_calls=AUTOTUNE)
    .map(augment,               num_parallel_calls=AUTOTUNE)
    .shuffle(buffer_size=1000, seed=SEED)
    .batch(BATCH_SIZE)
    .prefetch(AUTOTUNE)
)

val_ds = (
    raw_validation
    .map(resize_and_preprocess, num_parallel_calls=AUTOTUNE)
    .batch(BATCH_SIZE)
    .prefetch(AUTOTUNE)
)

test_ds = (
    raw_test
    .map(resize_and_preprocess, num_parallel_calls=AUTOTUNE)
    .batch(BATCH_SIZE)
    .prefetch(AUTOTUNE)
)

print("tf.data pipelines built successfully!")

"""Visualise Sample Training Images"""

display_ds = raw_train.map(lambda img, lbl: (tf.image.resize(img, IMG_SIZE), lbl))
images, labels = next(iter(display_ds.batch(12)))

plt.figure(figsize=(14, 6))
for i in range(12):
    plt.subplot(2, 6, i + 1)
    plt.imshow(images[i].numpy().astype('uint8'))
    plt.title(CLASS_NAMES[labels[i].numpy()], fontsize=11)
    plt.axis('off')
plt.suptitle('Sample Training Images (before augmentation)', fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

"""Build the Model"""

#   Architecture:
#     Input (150x150x3)
#       └─► VGG16 Conv Layers  [FROZEN — ImageNet weights]
#             └─► GlobalAveragePooling2D
#                   └─► Dense(256, ReLU) + Dropout(0.5)
#                         └─► Dense(128, ReLU) + Dropout(0.3)
#                               └─► Dense(2, Softmax)  ← cat / dog
# ─────────────────────────────────────────────────────────────────────────────

base_model = VGG16(
    weights='imagenet',
    include_top=False,           # exclude original FC layers
    input_shape=(*IMG_SIZE, 3)
)

# Freeze all conv layers — preserve ImageNet features
base_model.trainable = False
frozen_count = sum(1 for l in base_model.layers if not l.trainable)
print(f"VGG16 layers frozen : {frozen_count}/{len(base_model.layers)}")

# Custom classification head
x      = base_model.output
x      = GlobalAveragePooling2D(name='gap')(x)
x      = Dense(256, activation='relu', name='fc1')(x)
x      = Dropout(0.5, name='drop1')(x)
x      = Dense(128, activation='relu', name='fc2')(x)
x      = Dropout(0.3, name='drop2')(x)
output = Dense(NUM_CLASSES, activation='softmax', name='predictions')(x)

model = Model(inputs=base_model.input, outputs=output, name='VGG16_CatDog')

# Compile — SGD with momentum as specified in the assignment
model.compile(
    optimizer=SGD(learning_rate=0.001, momentum=0.9),
    loss='sparse_categorical_crossentropy',   # integer labels (0=cat, 1=dog)
    metrics=['accuracy']
)

model.summary()

"""Train the Model"""

callbacks = [
    EarlyStopping(
        monitor='val_accuracy',
        patience=4,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=2,
        min_lr=1e-6,
        verbose=1
    ),
    ModelCheckpoint(
        filepath='best_model.keras',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    )
]

history = model.fit(
    train_ds,
    epochs=EPOCHS,
    validation_data=val_ds,
    callbacks=callbacks,
    verbose=1
)

print("\n✅ Training complete!")

"""Plot Training History"""

def plot_history(hist):
    acc      = hist.history['accuracy']
    val_acc  = hist.history['val_accuracy']
    loss     = hist.history['loss']
    val_loss = hist.history['val_loss']
    epochs_range = range(1, len(acc) + 1)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].plot(epochs_range, acc,     'b-o', label='Train Accuracy')
    axes[0].plot(epochs_range, val_acc, 'r-o', label='Val Accuracy')
    axes[0].set_title('Model Accuracy', fontsize=14)
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Accuracy')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    axes[1].plot(epochs_range, loss,     'b-o', label='Train Loss')
    axes[1].plot(epochs_range, val_loss, 'r-o', label='Val Loss')
    axes[1].set_title('Model Loss', fontsize=14)
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Loss')
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.suptitle('Training & Validation Metrics', fontsize=16, y=1.02)
    plt.tight_layout()
    plt.show()

plot_history(history)

"""Evaluate on the Test Set"""

model.load_weights('best_model.keras')

test_loss, test_acc = model.evaluate(test_ds, verbose=0)
print(f"\n{'='*40}")
print(f"  Test Accuracy : {test_acc*100:.2f}%")
print(f"  Test Loss     : {test_loss:.4f}")
print(f"{'='*40}")

# Classification Report & Confusion Matrix
y_true, y_pred = [], []

for imgs, lbls in test_ds:
    preds = model.predict(imgs, verbose=0)
    y_pred.extend(np.argmax(preds, axis=1))
    y_true.extend(lbls.numpy())

y_true = np.array(y_true)
y_pred = np.array(y_pred)

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=CLASS_NAMES))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=CLASS_NAMES,
    yticklabels=CLASS_NAMES
)
plt.title('Confusion Matrix', fontsize=14)
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.show()

"""Predict on New Images"""

def predict_image(img_path: str) -> dict:
    """
    Classify a single image as 'cat' or 'dog'.

    Parameters
    ----------
    img_path : str
        Local path to the image file (JPEG, PNG, etc.)

    Returns
    -------
    dict with keys: predicted_class, confidence, all_probabilities
    """
    img       = load_img(img_path, target_size=IMG_SIZE)
    img_array = img_to_array(img)                         # (150, 150, 3)
    img_array = np.expand_dims(img_array, axis=0)         # (1, 150, 150, 3)
    img_array = preprocess_input(img_array)

    probs     = model.predict(img_array, verbose=0)[0]    # shape (2,)
    class_idx = np.argmax(probs)

    result = {
        'predicted_class'  : CLASS_NAMES[class_idx],
        'confidence'       : float(probs[class_idx]) * 100,
        'all_probabilities': {cls: float(p) * 100
                              for cls, p in zip(CLASS_NAMES, probs)}
    }

    # Display image with prediction
    plt.figure(figsize=(4, 4))
    plt.imshow(mpimg.imread(img_path))
    title_color = '#2196F3' if result['predicted_class'] == 'cat' else '#FF5722'
    plt.title(
        f"Prediction : {result['predicted_class'].upper()}\n"
        f"Confidence : {result['confidence']:.1f}%",
        fontsize=13, color=title_color, fontweight='bold'
    )
    plt.axis('off')
    plt.tight_layout()
    plt.show()

    # Probability bar chart
    fig, ax = plt.subplots(figsize=(5, 2))
    colors = ['#2196F3', '#FF5722']
    bars   = ax.barh(CLASS_NAMES, [probs[0]*100, probs[1]*100],
                     color=colors, height=0.4)
    ax.set_xlim(0, 100)
    ax.set_xlabel('Probability (%)')
    ax.set_title('Class Probabilities')
    for bar, p in zip(bars, probs):
        ax.text(bar.get_width() + 1,
                bar.get_y() + bar.get_height() / 2,
                f'{p*100:.1f}%', va='center', fontsize=11)
    plt.tight_layout()
    plt.show()

    return result

#Upload from your machine

from google.colab import files

print("Upload an image to classify:")
uploaded = files.upload()

if uploaded:
    for filename in uploaded:
        result = predict_image(filename)
        print(f"\nResult: {result}")

"""Fine-Tune VGG16 Block 5"""

#   Unfreeze block5 and retrain at a very low LR for an extra ~2-5% accuracy.

for layer in base_model.layers:
    if layer.name.startswith('block5'):
        layer.trainable = True

trainable_count = sum(1 for l in model.layers if l.trainable)
print(f"Trainable layers after unfreezing block5: {trainable_count}")

model.compile(
    optimizer=SGD(learning_rate=1e-4, momentum=0.9),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

fine_tune_callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=3,
                  restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                      patience=2, min_lr=1e-7, verbose=1),
    ModelCheckpoint('best_finetuned_model.keras',
                    monitor='val_accuracy', save_best_only=True, verbose=1)
]

history_ft = model.fit(
    train_ds,
    epochs=10,
    validation_data=val_ds,
    callbacks=fine_tune_callbacks,
    verbose=1
)

plot_history(history_ft)

test_loss_ft, test_acc_ft = model.evaluate(test_ds, verbose=0)
print(f"\nFine-Tuned Test Accuracy : {test_acc_ft*100:.2f}%")
print(f"Fine-Tuned Test Loss     : {test_loss_ft:.4f}")

"""Save & Export the Final Model"""

model.save('cat_dog_vgg16_final.keras')
print("Model saved  →  cat_dog_vgg16_final.keras")

model.export('cat_dog_savedmodel')
print("SavedModel exported  →  cat_dog_savedmodel/")

from google.colab import files
files.download('cat_dog_vgg16_final.keras')

# SUMMARY
# ─────────────────────────────────────────────────────────────────────────────
# Step  1  →  Libraries installed, seeds set, constants defined
# Step  2  →  Cats vs Dogs dataset via tensorflow_datasets (no Kaggle needed)
# Step  3  →  tf.data pipelines: VGG16 preprocessing + 5 augmentation ops
# Step  4  →  Frozen VGG16 base + custom head: GAP → 256 → 128 → Softmax(2)
# Step  5  →  Trained with SGD+momentum, EarlyStopping, ReduceLROnPlateau
# Step  6  →  Accuracy & loss curves plotted
# Step  7  →  Test evaluation: accuracy, classification report, confusion matrix
# Step  8  →  predict_image() & predict_from_url() for single-image inference
# Step  9  →  Optional fine-tuning of VGG16 block5 at lr=1e-4
# Step 10  →  Model saved in .keras and SavedModel formats
#
# Expected accuracy:  ~90-95% (frozen base)  |  ~95-97% (after fine-tuning)
# ─────────────────────────────────────────────────────────────────────────────